### ISSUE TITLE
Timer for each turn

### ISSUE THREAD

**Issue by pranavmodx** [subins2000/vett#13]
It would be great to have a timer for each turn of the players (say 15-20 sec) to make it more challenging to play. Players will have to make the move within that time or they lose on time (or they get a warning).
Even if this isn't planned, would this work? (considering latency and other factors)

**Comment by subins2000** [comment]
This would indeed make the game more interesting and challenging. Since it's P2P, each client would themselves determine if the timer runs out or not. There would be some delay because of that : A line drawn at the last second would reach the other players after the timer runs out, but that can be still be made valid.

Yes, will try to implement this. Thanks @pranavmodx :)

**Comment by subins2000** [comment]
Done, this has been implemented
